### PR TITLE
Fix v0.174.0 API deprecations

### PR DESCRIPTION
**Pull request by mndrix**
This pull request repairs all API deprecations as of Atom v0.174.0  I tried to keep the changes as small as possible but some of them are necessarily far reaching.

### CODE REVIEW

**Comment by mndrix** [comment]
Please don't merge this pull request yet.  There's a mistake somewhere such that making an atomic-emacs edit in one buffer accidentally modifies other buffers (sometimes).  I'll look into it.

**Comment by avendael** [comment]
Thanks for this and for the heads up. I'm planning to test this out first before merging it since it's a pretty big diff. Good job on eliminating the deprecations!

**Comment by mndrix** [comment]
I was able to fix the problem with accidental edits to multiple buffers by replacing `@editor` with `atom.workspace.getActiveTextEditor()` throughout the 'AtomicEmacs` class.  Although this works great in Atom, it breaks many of the specs.

I spent about an hour yesterday trying to make the specs pass, but had no success.  I won't be able to devote any time to this for the next 1-2 weeks.  Anyone else is welcome to pick up where I left off.  I can push my unfinished changes to this pull request, if that's helpful.

**Comment by avendael** [comment]
Yes, please do push the changes. Since this PR fixes deprecations, the specs might also be outdated and might also need to get fixed.

**Comment by mndrix** [comment]
I've pushed the `getActiveTextEditor()` changes which cause specs to fail.

**Comment by chancila** [comment]
Hey fixed up the specs for you:
https://github.com/avendael/atomic-emacs/pull/52

**Comment by avendael** [comment]
@mndrix @chancila thanks for the great work on this! Closing this in favor of https://github.com/avendael/atomic-emacs/pull/52.

**Pull request closed without merging**
