### PR TITLE
Fix deprecated spec usage

### PR DESCRIPTION
**Pull request by chancila**
Took mndrix's fork and fixed up the specs

### CODE REVIEW

**Comment by avendael** [comment]
Perfect, thank you for this! I'll release a new version tonight :+1:

**Comment by chancila** [comment]
btw the mark support is kinda buggy, it might be due to mndrix's change with getActiveTextEditor. At the moment there's also some private api use in the mark code which I'm looking into cleaning up.

**Comment by avendael** [comment]
I tried it out locally and it seems good to me, but I might be missing
something. How can I reproduce the bug?

**Comment by chancila** [comment]
maybe it's just me but toggling the mark in place doesn't disable it for me, so selection remains active until I perform a buffer modification, kinda annoying.

**Comment by avendael** [comment]
Yeah, it's a bug. I just got into the habit of using ctrl-g to cancel the mark, which is why I haven't noticed.

**Pull request merged**
