### PR TITLE
omit up/down/left/right keyboard shortcuts supported by atom

### PR DESCRIPTION
**Pull request by deanmalmgren**
I'm sure there is probably additional code that could be removed, but if atom supports up/down/left/right arrows and ctrl+{p,n,b,f} keys, it seems to add more bugs than it is worth to include these keybindings here. Testing locally for the past few days, this appears to address #37.

### CODE REVIEW

**Comment by mndrix** [comment]
I think this will cause problems on Linux.  On that platform, [ctrl-n binds to application:new-file](https://github.com/atom/atom/blob/d524d25a436eae7f1203e2f0d1cdd4826ab9104f/keymaps/linux.cson#L26) by default.  It looks like [Windows is similar](https://github.com/atom/atom/blob/d524d25a436eae7f1203e2f0d1cdd4826ab9104f/keymaps/win32.cson#L29).

**Comment by mndrix** [comment]
I should clarify my earlier comment.  I think it's a good idea to use `core:move-right`, etc. instead of `atomic-emacs:forward-char`, etc.  We just need to make sure all platforms have the proper key bindings.

**Comment by deanmalmgren** [comment]
@mndrix Good points on the multi-platform issues; I didn't realize that. I just added back the bindings for `ctrl-{f,b,p,n}` and they map to the core movements.

**Comment by avendael** [comment]
Hello! Sorry if I came in late to the party, I was on vacation.

Is this working properly even with the mark activated? Historically, native atom keybindings do not work when the mark is activated, which is why we replicated those in `lib/atomic-emacs.coffee`. But I also recently fixed an issue that only involves deletions. It seems that the native atom keybindings can now work with the mark properly. I'll try this branch out as well :)

**Comment by avendael** [comment]
@deanmalmgren unfortunately, this breaks the mark behavior.

The correct behavior is to move line-by-line, as in this screenshot:

master

In the patch, the cursor will jump back to the mark point when the cursor is moved down and then back up:
patch1

It would be great if we can get this fixed. I also noticed that the cursor moves sideways only after two taps when the mark is active.

**Comment by deanmalmgren** [comment]
Thanks for having a look @avendael. I think this is unfortunately beyond my paygrade because I'm not exactly sure about all the atom internals (I'm a bit of a n00b). Its probably best to throw away this PR and start a fresh one that makes the changes in a manner that supports the mark feature.

**Comment by avendael** [comment]
You're welcome, and thanks for looking into the problem. #44 should solve the issue of native keybindings with a setting, although I suspect the same mark bug would still be in effect. I'm going to take a look into improving marks once I get a considerable chunk of time to do it.

**Pull request closed without merging**
